### ISSUE TITLE
keybind on "Mod4-<key>" does not always work

### ISSUE THREAD

**Issue by ayuanx** [BurntSushi/xgbutil#42]
It seems you have to press several times to get one successful trigger.
I suspect somehow the very first one is always eaten by X window system menu.

**Comment by BurntSushi** [comment]
I use `Mod4-<key>` bindings created by this library every day and they work as intended, with no additional keypresses required.

**Comment by ayuanx** [comment]
Does your X window start menu pop up when you press Mod4 (aka. super / win)?
Mine does.

So in key combinations like Mod4-z, the Mod4 is eaten by start menu.
However, if you press and release Mod4 to trigger the start menu popup first, then pressing Mod4-z works.

**Comment by BurntSushi** [comment]
There is no X window start menu. You clearly have other applications
competing for the same key bindings, so this isn't a problem with xgbutil.
