### ISSUE TITLE
[Question] Support for simulating keypresses?

### ISSUE THREAD

**Issue by thornycrackers** [BurntSushi/xgbutil#46]
Hello! Thanks for this library and for taking the time to write out the examples as they have been very helpful. Currently I'm trying to make a bare bones a simple text expander. The first part was easy to do modifying the example the `keypress-english` examples so I could listen for the text. I didn't any examples for simulating a keypress and was wondering if this library supports that and if not where to start looking for something like that? I have some very simple working C code:

```
#include <stdio.h>
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/extensions/XTest.h>
#include <unistd.h>

#define XK_c                             0x0063
#define XK_d                             0x0064
#define XK_h                             0x0068
#define XK_o                             0x006f
#define XK_y                             0x0079 
#define XK_at                            0x0040
#define XK_Shift_L                       0xffe1

int main() {
  Display *dpy;
  dpy = XOpenDisplay(NULL);
  sleep(2);

  KeyCode code = XKeysymToKeycode(dpy, XK_c);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);
  code = XKeysymToKeycode(dpy, XK_o);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);
  code = XKeysymToKeycode(dpy, XK_d);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);
  code = XKeysymToKeycode(dpy, XK_y);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);

  // Make sure to send shift
  code = XKeysymToKeycode(dpy, XK_Shift_L);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  code = XKeysymToKeycode(dpy, XK_at);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);
  code = XKeysymToKeycode(dpy, XK_Shift_L);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);
  // No more shift
  //
  code = XKeysymToKeycode(dpy, XK_h);
  XTestFakeKeyEvent(dpy, code, True, CurrentTime);
  XTestFakeKeyEvent(dpy, code, False, CurrentTime);

  XFlush( dpy );
  XCloseDisplay( dpy );

  return 0;
}
```
After that I updated this code to use something a bit more robust so I could call the C code from go with the following:
```
#include <stdio.h>
#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/extensions/XTest.h>


int x11_key(char *zh){
  Display *dpy;
  dpy = XOpenDisplay(NULL);

  KeySym sym = XStringToKeysym(zh);
  int min, max, numcodes;
  XDisplayKeycodes(dpy,&min,&max);
  KeySym *keysym;
  keysym = XGetKeyboardMapping(dpy,min,max-min+1,&numcodes);
  keysym[(max-min-1)*numcodes]=sym;
  XChangeKeyboardMapping(dpy,min,numcodes,keysym,(max-min));
  XFree(keysym);
  XFlush( dpy );
  KeyCode code = XKeysymToKeycode(dpy,sym);
  XTestFakeKeyEvent(dpy, code, True, 1);
  XTestFakeKeyEvent(dpy, code, False, 1);

  XFlush( dpy );
  XCloseDisplay( dpy );

  return 0;
}
```
 
Which worked pretty well but when I would send a string like `example@email.com` the `@` symbol would get messed up in programs other that the terminal I was running the code in. I searched around and saw the comment posted on https://stackoverflow.com/questions/26446184/control-the-mouse-and-keyboard-golang  that said `For X11 at least, there's no reason to use a C library. XGB is a native implementation of the X client protocol.` which lead me here but I couldn't find and examples that simulated keypresses.

**Comment by BurntSushi** [comment]
The last commit to this project was almost 3 years ago, and the last time I used this project in anger was probably 6 years ago. It's effectively unmaintained other than keeping it working as-is since I still use it every day. It's effectively "complete."

As for your question, no, this library doesn't provide it. This library just provides helper functions corresponding to a small sampling of the X protocol, particularly, the aspects that help facilitate building a window manager.

The C code you've shown uses the `XTest` _extension_ to the core X protocol. There is nothing in `xgbutil` that uses XTest, AFAIK. Therefore, you'll need to use the xgb bindings to that extension yourself: https://github.com/BurntSushi/xgb/blob/master/xtest/xtest.go --- I don't know whether they work or not.

**Comment by thornycrackers** [comment]
Thanks for replying so quickly. I will take a look at the xtest.go. Thank you!
