### ISSUE TITLE
NO LICENSE, godoc shows no doc

### ISSUE THREAD

**Issue by tobyweb3x** [BurntSushi/xgbutil#56]
The repo lacks a license file, so godoc does not display the docs.
![Screenshot from 2024-02-16 09-21-14](https://github.com/BurntSushi/xgbutil/assets/73890077/49db7419-3b02-4356-9d49-aea8c6768556)

**Comment by BurntSushi** [comment]
> The repo lacks a license file

[It clearly does not.](https://github.com/BurntSushi/xgbutil/blob/master/COPYING)

Your screenshot even clearly indicates that godoc has identified the license!
